{
 "title": "Метрики node_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",mode=\"idle\"}[15s])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 5",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 15",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободная ОЗУ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node_exporter:9100\", job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободное место на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda2\", instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}