---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.22.255
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.0.88
nginx-lighthouse:
  hosts:
    nginx-lighthouse-01:
      ansible_host: 158.160.13.212
     
